Added a README file
RitvikSangwan/First-Commit pull request #2
Opened 2021-04-28 06:07 UTC by ritviksangwan13

Added a README file for the project

2021-04-28 06:33 UTC, RitvikSangwan commented
This README is too short. Can you elaborate more?

2021-04-30 02:42 UTC, RitvikSangwan requested changes
Appreciate your follow up here.

2021-04-30 02:43 UTC, RitvikSangwan requested changes
Make it more explanatory

2021-04-30 02:43 UTC, RitvikSangwan commented on README.md
> +Added more description.
Add more description here.

2021-04-30 03:06 UTC, ritviksangwan13 commented on README.md
> +Added more description.
I have added more description

2021-04-30 03:07 UTC, RitvikSangwan approved these changes

2021-04-30 07:06 UTC, merged